TELEGRAM:
  BOT_TOKEN: "7"
  APP_URL: "https://linker.loca.lt"
SERVER:
  HOST: ""
  PORT: "8080"
DATABASE:
  HOST: "localhost"
  PORT: "5432"
  USER: "linker"
  PASSWORD: "linker_password"
  NAME: "linker_db"