TELEGRAM:
  BOT_TOKEN: "7799792319:AAEaby4Qhaoh4ioeuBG3dHUIrQmk6SUihM8"
  APP_URL: "https://nice-crab-83.loca.lt"
SERVER:
  HOST: ""
  PORT: "8080"
DATABASE:
  HOST: "localhost"
  PORT: "5432"
  USER: "linker"
  PASSWORD: "linker_password"
  NAME: "linker_db"