version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: linker
      POSTGRES_PASSWORD: linker_password
      POSTGRES_DB: linker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - linker_network

volumes:
  postgres_data:

networks:
  linker_network:
